pipelines:
  custom: 
    dev-deploy:
      - step:
          image: mesosphere/aws-cli:latest
          deployment: test
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - echo "mdot" > deploy.txt
            - echo "mdot-dev-${BITBUCKET_BUILD_NUMBER}" > version.txt
            - aws s3 cp deploy.txt s3://permanent-repos/dev/deploy.txt
            - aws s3 cp version.txt s3://permanent-repos/dev/version.txt
  pull-requests:
    '**':
      - step:
          name: Unit tests
          image: permanentorg/mdot:test
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - cd /data/www
            - ln -s /data/www/* $BITBUCKET_CLONE_DIR/../
            - cd $BITBUCKET_CLONE_DIR
            - npm install --unsafe-perm
            - npm run test_build
  branches:
    dev:
      - step:
          name: Build and upload to S3
          image: permanentorg/mdot:build
          deployment: dev
          caches:
            - node
          script:
            - declare -x VERSION=mdot@$(jq -r '.version' package.json)
            - cd /data/www
            - ln -s /data/www/* $BITBUCKET_CLONE_DIR/../
            - cd $BITBUCKET_CLONE_DIR
            - npm install --unsafe-perm
            - npm run build_dev
            ## have to make these goofy dupe directories to match paths for sentry
            - cp -r dist/mdot dist/m
            - cp -r dist/mdot dist/share
            - cp -r dist/mdot dist/p
            - npm install -g @sentry/cli --unsafe-perm
            - export SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
            - sentry-cli releases set-commits $VERSION --auto
            - sentry-cli releases $VERSION upload-sourcemaps --rewrite --validate --verbose --strip-common-prefix ./dist/ --ignore mdot
            - rm -r dist/m dist/share dist/p
            - rm dist/mdot/*.map
            - cd ..
            - mkdir mdot
            - mv $BITBUCKET_CLONE_DIR/dist mdot/dist
            - tar -czvf mdot.tar.gz mdot
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp mdot.tar.gz s3://permanent-repos/dev/mdot.tar.gz 
      - step:
          name: Deploy dev (optional)
          image: mesosphere/aws-cli:latest
          trigger: manual
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - echo "mdot" > deploy.txt
            - echo "mdot-dev-${BITBUCKET_BUILD_NUMBER}" > version.txt
            - aws s3 cp deploy.txt s3://permanent-repos/dev/deploy.txt
            - aws s3 cp version.txt s3://permanent-repos/dev/version.txt
    feature/full-responsive:
      - step:
          name: Build and upload to S3
          image: permanentorg/mdot:build
          deployment: demo
          caches:
            - node
          script:
            - cd /data/www
            - git clone git@bitbucket.org:permanent-org/deploy.git
            - ln -s /data/www/* $BITBUCKET_CLONE_DIR/../
            - cd $BITBUCKET_CLONE_DIR
            - npm install --unsafe-perm
            - npm run build_dev
            - cd ..
            - mkdir mdot-responsive
            - mv $BITBUCKET_CLONE_DIR/dist mdot-responsive/dist
            - tar -czvf mdot-responsive.tar.gz mdot-responsive
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp mdot-responsive.tar.gz s3://permanent-repos/dev/mdot-responsive.tar.gz 
            - ssh ubuntu@dev1.permanent.org 'bash -s' < deploy/scripts/mdot/deploy-responsive-dev.sh
    release/staging:
      - step:
          name: Build and upload to S3
          image: permanentorg/mdot:build
          deployment: staging
          caches:
            - node
          script:
            - declare -x VERSION=mdot@$(jq -r '.version' package.json)
            - cd /data/www
            - ln -s /data/www/* $BITBUCKET_CLONE_DIR/../
            - cd $BITBUCKET_CLONE_DIR
            - npm install --unsafe-perm
            - npm run build_staging
            ## have to make these goofy dupe directories to match paths for sentry
            - cp -r dist/mdot dist/m
            - cp -r dist/mdot dist/share
            - cp -r dist/mdot dist/p
            - npm install -g @sentry/cli --unsafe-perm
            - export SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
            - sentry-cli releases set-commits $VERSION --auto
            - sentry-cli releases $VERSION upload-sourcemaps --rewrite --validate --verbose --strip-common-prefix ./dist/ --ignore mdot
            - rm -r dist/m dist/share dist/p
            - rm dist/mdot/*.map
            - cd ..
            - mkdir mdot
            - mv $BITBUCKET_CLONE_DIR/dist mdot/dist
            - tar -czvf mdot.tar.gz mdot
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp mdot.tar.gz s3://permanent-repos/staging/mdot.tar.gz
    release/production:
      - step:
          name: Build and upload to S3
          image: permanentorg/mdot:build
          deployment: production
          caches:
            - node
          script:
            - git remote set-url origin ${BITBUCKET_GIT_SSH_ORIGIN}
            - declare -x VERSION=mdot@$(jq -r '.version' package.json)
            - cd /data/www
            - ln -s /data/www/* $BITBUCKET_CLONE_DIR/../
            - cd $BITBUCKET_CLONE_DIR
            - npm install --unsafe-perm
            - npm run build
           ## have to make these goofy dupe directories to match paths for sentry
            - cp -r dist/mdot dist/m
            - cp -r dist/mdot dist/share
            - cp -r dist/mdot dist/p
            - rm dist/mdot/*.map
            - npm install -g @sentry/cli --unsafe-perm
            - export SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
            - sentry-cli releases set-commits $VERSION --auto
            - sentry-cli releases $VERSION upload-sourcemaps --rewrite --validate --verbose --strip-common-prefix ./dist/ --ignore mdot
            - rm -r dist/m dist/share dist/p
            - git config --global user.email "engineering@permanent.org"
            - git config --global user.name "Bitbucket Pipelines"
            - git tag $VERSION
            - git push origin --tags
            - cd ..
            - mkdir mdot
            - mv $BITBUCKET_CLONE_DIR/dist mdot/dist
            - tar -czvf mdot.tar.gz mdot
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp mdot.tar.gz s3://permanent-repos/production/mdot.tar.gz
