image: sandurz/node-git-aws:with-chrome

pipelines:
  pull-requests:
    '**':
      - step:
          image: sandurz/node-git-aws:with-chrome
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - ln -s $BITBUCKET_CLONE_DIR /data/www/mdot
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp --quiet s3://permanent-repos/dev/files.tar.gz /data/tmp/files.tar.gz
            - tar -xzf /data/tmp/files.tar.gz -C /data/www
            - cd /data/www/mdot
            - npm install
            - npm run test_build
  branches:
    dev:
      - step:
          image: sandurz/node-git-aws:latest
          caches:
            - node
          script:
            - ln -s $BITBUCKET_CLONE_DIR /data/www/mdot
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp --quiet s3://permanent-repos/dev/files.tar.gz /data/tmp/files.tar.gz
            - tar -xzf /data/tmp/files.tar.gz -C /data/www
            - cd /data/www/mdot
            - npm install
            - npm run build
            - rm -rf node_modules
            - cd ..
            - tar -czf mdot.tar.gz mdot
            - aws s3 cp mdot.tar.gz s3://permanent-repos/dev/mdot.tar.gz 