pipelines:
  custom: 
    dev-deploy:
      - step:
          image: mesosphere/aws-cli:latest
          deployment: test
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - echo "mdot" > deploy.txt
            - echo "mdot-dev-${BITBUCKET_BUILD_NUMBER}" > version.txt
            - aws s3 cp deploy.txt s3://permanent-repos/dev/deploy.txt
            - aws s3 cp version.txt s3://permanent-repos/dev/version.txt
  pull-requests:
    '**':
      - step:
          name: Unit tests
          image: permanentlegacy/node-git-aws:with-chrome
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - cd /data/www
            - git clone git@bitbucket.org:permanent-org/files.git
            - ln -s /data/www/* $BITBUCKET_CLONE_DIR/../
            - cd $BITBUCKET_CLONE_DIR
            - npm install
            - npm run test_build
  branches:
    dev:
      - step:
          name: Build and upload to S3
          image: permanentlegacy/node-git-aws:latest
          deployment: dev
          caches:
            - node
          script:
            - cd /data/www
            - git clone git@bitbucket.org:permanent-org/files.git
            - ln -s /data/www/* $BITBUCKET_CLONE_DIR/../
            - cd $BITBUCKET_CLONE_DIR
            - npm install
            - npm run build_dev
            - cd ..
            - mkdir mdot
            - mv $BITBUCKET_CLONE_DIR/dist mdot/dist
            - tar -czvf mdot.tar.gz mdot
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp mdot.tar.gz s3://permanent-repos/dev/mdot.tar.gz 
      - step:
          name: Deploy dev (optional)
          image: mesosphere/aws-cli:latest
          trigger: manual
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - echo "mdot" > deploy.txt
            - echo "mdot-dev-${BITBUCKET_BUILD_NUMBER}" > version.txt
            - aws s3 cp deploy.txt s3://permanent-repos/dev/deploy.txt
            - aws s3 cp version.txt s3://permanent-repos/dev/version.txt
    feature/full-responsive:
      - step:
          name: Build and upload to S3
          image: permanentlegacy/node-git-aws:latest
          deployment: demo
          caches:
            - node
          script:
            - cd /data/www
            - git clone git@bitbucket.org:permanent-org/files.git
            - git clone git@bitbucket.org:permanent-org/deploy.git
            - ln -s /data/www/* $BITBUCKET_CLONE_DIR/../
            - cd $BITBUCKET_CLONE_DIR
            - npm install
            - npm run build_dev
            - cd ..
            - mkdir mdot-responsive
            - mv $BITBUCKET_CLONE_DIR/dist mdot-responsive/dist
            - tar -czvf mdot-responsive.tar.gz mdot-responsive
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp mdot-responsive.tar.gz s3://permanent-repos/dev/mdot-responsive.tar.gz 
            - ssh ubuntu@dev1.permanent.org 'bash -s' < deploy/scripts/mdot/deploy-responsive-dev.sh
    release/staging:
      - step:
          name: Build and upload to S3
          image: permanentlegacy/node-git-aws:latest
          deployment: staging
          caches:
            - node
          script:
            - cd /data/www
            - git clone -b release/staging --single-branch git@bitbucket.org:permanent-org/files.git
            - ln -s /data/www/* $BITBUCKET_CLONE_DIR/../
            - cd $BITBUCKET_CLONE_DIR
            - npm install
            - npm run build_staging
            - cd ..
            - mkdir mdot
            - mv $BITBUCKET_CLONE_DIR/dist mdot/dist
            - tar -czvf mdot.tar.gz mdot
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp mdot.tar.gz s3://permanent-repos/staging/mdot.tar.gz
    release/production:
      - step:
          name: Build and upload to S3
          image: permanentlegacy/node-git-aws:latest
          deployment: production
          caches:
            - node
          script:
            - cd /data/www
            - git clone -b release/production --single-branch git@bitbucket.org:permanent-org/files.git
            - ln -s /data/www/* $BITBUCKET_CLONE_DIR/../
            - cd $BITBUCKET_CLONE_DIR
            - npm install
            - npm run build
            - cd ..
            - mkdir mdot
            - mv $BITBUCKET_CLONE_DIR/dist mdot/dist
            - tar -czvf mdot.tar.gz mdot
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp mdot.tar.gz s3://permanent-repos/production/mdot.tar.gz 