pipelines:
  custom: 
    dev-deploy:
      - step:
          image: mesosphere/aws-cli:latest
          deployment: test
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - echo "mdot" > deploy.txt
            - echo "mdot-dev-${BITBUCKET_BUILD_NUMBER}" > version.txt
            - aws s3 cp deploy.txt s3://permanent-repos/dev/deploy.txt
            - aws s3 cp version.txt s3://permanent-repos/dev/version.txt
  pull-requests:
    '**':
      - step:
          name: Unit tests
          image: sandurz/node-git-aws:with-chrome
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp --quiet s3://permanent-repos/dev/files.tar.gz /data/tmp/files.tar.gz
            - cd ..
            - tar -xzf /data/tmp/files.tar.gz
            - cd $BITBUCKET_CLONE_DIR
            - npm install
            - npm run test_build
  branches:
    dev:
      - step:
          name: Build and upload to S3
          image: sandurz/node-git-aws:latest
          caches:
            - node
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws s3 cp --quiet s3://permanent-repos/dev/files.tar.gz /data/tmp/files.tar.gz
            - cd ..
            - tar -xzf /data/tmp/files.tar.gz
            - cd $BITBUCKET_CLONE_DIR
            - npm install
            - npm run build
            - cd ..
            - mkdir mdot
            - mv $BITBUCKET_CLONE_DIR/dist mdot/dist
            - tar -czvf mdot.tar.gz mdot
            - aws s3 cp mdot.tar.gz s3://permanent-repos/dev/mdot.tar.gz 