image: sandurz/node-git-aws:latest

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - export AWS_ACCESS_KEY_ID=$AWS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET
          - export AWS_DEFAULT_REGION=$AWS_REGION
          - aws s3 cp s3://permanent-repos/dev/files.tar.gz /data/tmp/files.tar.gz
          - cd ..
          - tar -xzf /data/tmp/files.tar.gz
          - cd $BITBUCKET_CLONE_DIR
          - npm install
          - npm run test_build
          - npm run build
