FROM php:8.3.9-apache-bookworm

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_ACCESS_SECRET
ARG AWS_REGION

ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_ACCESS_SECRET=$AWS_ACCESS_SECRET
ENV AWS_REGION=$AWS_REGION

# gettext is needed for envsubst
RUN apt update \
  && apt install -y \
  gettext \
  awscli \
  && apt clean

COPY web-app/dist /data/www/mdot/dist
COPY back-end/api /data/www/api

# apache config files
COPY infrastructure/templates/etc/apache2/conf-available/* /etc/apache2/conf-available/
COPY infrastructure/templates/etc/apache2/sites-available/local.permanent.conf /temp/etc/apache2/sites-available/local.permanent.conf
RUN envsubst < /temp/etc/apache2/sites-available/local.permanent.conf > /etc/apache2/sites-available/local.permanent.conf

# AWS credentials
COPY infrastructure/templates/var/www/.aws/* /temp/var/www/.aws/
RUN mkdir /var/www/.aws/
RUN envsubst < /temp/var/www/.aws/credentials > /var/www/.aws/credentials
RUN envsubst < /temp/var/www/.aws/config > /var/www/.aws/config

# todo -> find what this does
RUN echo "local"  > /data/www/host.txt

RUN aws s3 cp --recursive s3://permanent-local/certs /etc/ssl

# this allows apache to write logs in this folder
RUN mkdir -p /var/log/permanent \
  && chown -R www-data:www-data /var/log/permanent

RUN a2enmod proxy_http
RUN a2enmod ssl

RUN a2dissite 000-default

RUN a2ensite local.permanent

RUN a2enmod \
  rewrite \
  expires \
  headers \
  http2 \
  proxy_fcgi
RUN a2enconf \
  charset \
  global-server-name \
  no-etag \
  performance

WORKDIR /data/www/mdot/dist
