name: Prod build and upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      google-api-key: ${{ secrets.GOOGLE_API_KEY_PROD }}
      firebase-api-key: ${{ secrets.FIREBASE_API_KEY_PROD }}
      stripe-api-key: ${{ secrets.STRIPE_LIVE_KEY }}
      recaptcha-api-key: ${{ secrets.RECAPTCHA_API_KEY }}
      fusionauth-host: ${{ secrets.FUSIONAUTH_PROD_HOST }}
      stela-domain: ${{ secrets.STELA_DOMAIN_PROD }}
      mixpanel-token: ${{ secrets.MIXPANEL_TOKEN_PROD }}
      fontawesome-token: ${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}
    with:
      build-command: "build"
      artifact-name: "prod"

  build-storybook:
    uses: ./.github/workflows/build-storybook.yml
    secrets: inherit
    with:
      artifact-name: "prod"

  upload-sourcemaps:
    needs: build
    uses: ./.github/workflows/upload-sourcemaps.yml
    secrets: inherit
    with:
      artifact-name: "prod"

  upload-code:
    needs: [build, build-storybook]
    uses: ./.github/workflows/upload-code.yml
    secrets: inherit
    with:
      artifact-name: "prod"
      s3-destination: "s3://permanent-repos/prod/mdot.tar.gz"
