name: Dev build and deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      google-api-key: ${{ secrets.GOOGLE_API_KEY_DEV }}
      firebase-api-key: ${{ secrets.FIREBASE_API_KEY_DEV }}
      stripe-api-key: ${{ secrets.STRIPE_TEST_KEY }}
      recaptcha-api-key: ${{ secrets.RECAPTCHA_API_KEY_DEV }}
      stela-domain: ${{ secrets.STELA_DOMAIN_DEV }}
      mixpanel-token: ${{ secrets.MIXPANEL_TOKEN_DEV }}
      fusionauth-host: ${{ secrets.FUSIONAUTH_HOST_DEV }}
      fontawesome-token: ${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}
    with:
      build-command: 'build:dev'
      artifact-name: 'dev'

  build-storybook:
    uses: ./.github/workflows/build-storybook.yml
    secrets: inherit
    with:
      artifact-name: 'dev'

  upload-sourcemaps:
    needs: build
    uses: ./.github/workflows/upload-sourcemaps.yml
    secrets: inherit
    with:
      artifact-name: 'dev'

  upload-code:
    needs: [build, build-storybook]
    uses: ./.github/workflows/upload-code.yml
    secrets: inherit
    with:
      artifact-name: 'dev'
      s3-destination: 's3://permanent-repos/dev/mdot.tar.gz'

  deploy:
    needs: [upload-code, upload-sourcemaps]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dev deploy
        run: curl -X POST -H 'Accept:application/vnd.github.v3+json' -H 'Authorization:Bearer ${{ secrets.PERMANENT_DEPLOY_PAT }}' https://api.github.com/repos/PermanentOrg/infrastructure/actions/workflows/deploy-dev.yml/dispatches -d '{"ref":"main"}'
