name: Staging build and upload

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      google-api-key: ${{ secrets.GOOGLE_API_KEY_STAGING }}
      firebase-api-key: ${{ secrets.FIREBASE_API_KEY_STAGING }}
      stripe-api-key: ${{ secrets.STRIPE_TEST_KEY }}
      recaptcha-api-key: ${{ secrets.RECAPTCHA_API_KEY_DEV }}
      stela-domain: ${{ secrets.STELA_DOMAIN_STAGING }}
      mixpanel-token: ${{ secrets.MIXPANEL_TOKEN_DEV }}
      fusionauth-host: ${{ secrets.FUSIONAUTH_HOST_DEV }}
      fontawesome-token: ${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}
    with:
      build-command: 'build:staging'
      artifact-name: 'staging'

  build-storybook:
    uses: ./.github/workflows/build-storybook.yml
    secrets: inherit
    with:
      artifact-name: 'staging'

  upload-sourcemaps:
    needs: build
    uses: ./.github/workflows/upload-sourcemaps.yml
    secrets: inherit
    with:
      artifact-name: 'staging'

  upload-code:
    needs: [build, build-storybook]
    uses: ./.github/workflows/upload-code.yml
    secrets: inherit
    with:
      artifact-name: 'staging'
      s3-destination: 's3://permanent-repos/staging/mdot.tar.gz'
