name: QA Instructions
on:
  pull_request:
    types: [labeled, synchronize]

permissions:
  pull-requests: write
  models: read

jobs:
  qa-instructions:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'QA')
    steps:
      - uses: BadIdeaFactory/qa-instructions-action@v0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
